apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default
roleRef:
  kind: Role
  name: Role
  apiGroup: rbac.authorization.k8s.io

